// Optional browser smoke test. Requires Playwright and installed Microsoft Edge.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:4173');
  await page.screenshot({ path: path.join(os.tmpdir(), 'museflow-desktop.png'), fullPage: true });
  await page.locator('#prompt').fill('测试创作：淡蓝色海面与极简拱门');
  await page.getByRole('button', { name: '生成图像', exact: true }).click();
  await page.getByRole('button', { name: '查看 测试创作：淡蓝色海面与极简拱门', exact: true }).click();
  await page.locator('[role=dialog] .badge.SUCCEEDED').waitFor({ timeout: 12000 });
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: '下载示例图' }).click();
  assert.match((await downloadEvent).suggestedFilename(), /^MF-.*demo.svg$/);
  await page.getByRole('button', { name: '关闭弹窗' }).click();
  console.log('PASS: create, queue, success, detail, download');
  await page.getByRole('button', { name: '演示设置' }).click();
  await page.locator('#scenario').selectOption('retry');
  await page.getByRole('button', { name: '关闭弹窗' }).click();
  await page.locator('#prompt').fill('测试自动重试');
  await page.getByRole('button', { name: '生成图像', exact: true }).click();
  await page.getByRole('button', { name: '查看 测试自动重试', exact: true }).click();
  await page.locator('[role=dialog] .badge.SUCCEEDED').waitFor({ timeout: 14000 });
  assert.match(await page.locator('.timeline').innerText(), /第 2 次超时/);
  await page.keyboard.press('Escape');
  console.log('PASS: two automatic retries then success');
  await page.getByRole('button', { name: '演示设置' }).click();
  await page.locator('#scenario').selectOption('fail');
  await page.getByRole('button', { name: '关闭弹窗' }).click();
  await page.locator('#prompt').fill('测试永久失败');
  await page.getByRole('button', { name: '生成图像', exact: true }).click();
  await page.getByRole('button', { name: '查看 测试永久失败', exact: true }).click();
  await page.locator('[role=dialog] .badge.FAILED').waitFor({ timeout: 8000 });
  assert.match(await page.locator('.error-message').innerText(), /未执行自动重试/);
  await page.getByRole('button', { name: '修改描述', exact: true }).click();
  assert.equal(await page.locator('#prompt').inputValue(), '测试永久失败');
  await page.getByRole('button', { name: '失败', exact: true }).click();
  await page.getByRole('button', { name: '查看 暖色静物研究', exact: true }).click();
  await page.getByRole('button', { name: '重新尝试', exact: true }).click();
  await page.getByRole('button', { name: '查看 暖色静物研究 · 重试', exact: true }).click();
  assert.match(await page.locator('.detail-info').innerText(), /源任务/);
  await page.locator('[role=dialog] .badge.SUCCEEDED').waitFor({ timeout: 10000 });
  await page.getByRole('button', { name: '复用参数' }).click();
  assert.match(await page.locator('#prompt').inputValue(), /暖杏色背景/);
  await page.locator('#prompt').fill('测试永久失败');
  console.log('PASS: permanent failure edit path, linked service-failure retry, reuse');
  await page.getByRole('button', { name: '使用示例参考图' }).click();
  await page.locator('.ref-preview img').waitFor();
  await page.getByRole('button', { name: 'B · 引导式创建' }).click();
  assert.match(page.url(), /variant=B/);
  assert.equal(await page.locator('#prompt').inputValue(), '测试永久失败');
  assert.equal(await page.locator('.ref-preview img').count(), 1);
  await page.screenshot({ path: path.join(os.tmpdir(), 'museflow-focus.png'), fullPage: true });
  await page.getByRole('button', { name: 'C · 任务控制台' }).click();
  await page.locator('table').waitFor();
  await page.getByRole('button', { name: '新建任务', exact: true }).click();
  assert.equal(await page.locator('#prompt').inputValue(), '测试永久失败');
  await page.getByRole('button', { name: '关闭弹窗' }).click();
  await page.screenshot({ path: path.join(os.tmpdir(), 'museflow-console.png'), fullPage: true });
  console.log('PASS: three structural variants preserve draft and reference');
  await page.getByRole('button', { name: '任务历史' }).filter({ visible: true }).click();
  await page.locator('#search').fill('not-a-real-task');
  assert.match(await page.locator('.empty').innerText(), /没有找到/);
  await page.getByRole('button', { name: '清除筛选' }).click();
  await page.getByRole('button', { name: '第 2 页' }).click();
  assert.ok(await page.locator('.card').count() > 0);
  await page.getByRole('button', { name: '失败', exact: true }).click();
  assert.equal(await page.locator('.card').count(), 2);
  console.log('PASS: search, pagination, failed filter');
  await page.goto('http://127.0.0.1:4173/?variant=A');
  await page.getByRole('button', { name: '参考图生成', exact: true }).click();
  await page.getByRole('button', { name: '生成图像', exact: true }).click();
  assert.match(await page.locator('#toast').innerText(), /请先添加参考图/);
  await page.locator('#reference').setInputFiles({ name: 'reference.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64') });
  await page.locator('.ref-preview img').waitFor();
  assert.match(await page.locator('.ref-preview').innerText(), /reference.png/);
  await page.getByRole('button', { name: '移除参考图' }).click();
  console.log('PASS: reference requirement and real local file preview');
  await page.setViewportSize({ width: 390, height: 844 });
  for (const variant of ['A', 'B', 'C']) {
    await page.goto('http://127.0.0.1:4173/?variant=' + variant);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'no mobile horizontal overflow: ' + variant);
    await page.screenshot({ path: path.join(os.tmpdir(), 'museflow-mobile-' + variant + '.png'), fullPage: true });
  }
  assert.deepEqual(errors, []);
  console.log('PASS: mobile layouts, no browser JS errors');
  console.log('ALL BROWSER CHECKS PASSED');
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
